spring:
  cache:
    redis:
      cache-null-values: true
      use-key-prefix: true
      key-prefix: "${spring.application.name}:"
      time-to-live: 60000
    type: redis
    cache-names: cacheSample
  data:
    redis:
      repositories:
        enabled: true
  redis:
    database: 0
    lettuce:
      pool:
        max-active: 10
        min-idle: 0
        max-wait: 10000
      shutdown-timeout: 200000
    ssl: false
    host: localhost
    port: 5800
