spring:
  datasource:
#   url: "jdbc:h2:file:~/h2-db;DB_CLOSE_ON_EXIT=FALSE"
    url: "jdbc:h2:mem:web;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE"
    username: root
    password: 1
    driver-class-name: org.h2.Driver
    platform: h2
    type: com.zaxxer.hikari.HikariDataSource
    hikari: # refer to https://mp.weixin.qq.com/s?__biz=MzUzNTY4NTYxMA==&mid=2247483699&idx=1&sn=5efd1f9d872688eba0029c71b3668662&chksm=fa80f1b6cdf778a0bbd12ce5e97507d697058d7bc070082a8ca828c9910c1379ead43c7b9a05&scene=21#wechat_redirect
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      pool-name: hikariPool
      idle-timeout: 600000
    continue-on-error: true # Do not stop if an error occurs while initializing the database
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true  # print sql to console
        use_sql_comments: false
        format_sql: false
